import{a as m,S as w,i as n}from"./assets/vendor-30VqbI-A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const v=m.defaults.API_KEY="49359087-343ead2b9467da8fb57304bcb",P=m.defaults.baseURL="https://pixabay.com/api/";async function g(a,t){const r={params:{key:v,q:a.trim(),image_type:"photo",orientation:"horizontal",page:t,per_page:15,safesearch:"true"}},o=await m.get(P,r),{hits:e,totalHits:s}=o.data;return{hits:e,totalHits:s}}let u=null;function S(){y.innerHTML=""}function h(a){E(a)}function q(){f.classList.remove("hidden")}function c(){f.classList.add("hidden")}const y=document.querySelector(".gallery"),f=document.querySelector(".btn-more");function E(a=[]){const t=a.map(r=>`<li class="gallery-item">
        <a href="${r.largeImageURL}" class="gallery-item-link">
        <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="text-info">
        <p><b>Likes:</b>${r.likes}</p>
        <p><b>Views:</b>${r.views}</p>
        <p><b>Comments:</b>${r.comments}</p>
        <p><b>Downloads:</b>${r.downloads}</p>
        </div>
        </li>`).join("");y.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new w(".gallery a",{caption:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}const R=document.querySelector(".form"),b=document.querySelector(".loader"),L=document.querySelector(".loader-bottom");function T(){b.classList.remove("hidden")}function p(){b.classList.add("hidden")}function x(){L.classList.remove("hidden")}function A(){L.classList.add("hidden")}f.addEventListener("click",B);R.addEventListener("submit",$);let l=null,i=1;async function $(a){a.preventDefault(),i=1,S();const t=a.currentTarget,{searchText:r}=t.elements;if(l=r.value.trim(),!l){n.show({title:"⛔",message:"Please write a search query!",color:"yellow",position:"topRight"});return}T(),c();try{const{hits:o,totalHits:e}=await g(l,i);if(!Array.isArray(o)){console.error("Invalid response structure. Hits is not an array."),n.show({title:"⚠️",message:"Unexpected response format. Please try again later!",color:"yellow",position:"topRight"}),p();return}if(o.length===0){n.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),p();return}h(o),o.length<e?q():c(),t.reset()}catch(o){let e="An unexpected error occurred. Please try again later!";o.response?e=`Server Error: ${o.response.data.message||o.message}`:o.request&&(e="Network Error: Failed to reach the server. Please check your internet connection."),n.show({title:"⚠️",message:e,color:"red",position:"topRight"}),console.error("Error:",o.message)}p()}async function B(a){i+=1,x();try{const{hits:t,totalHits:r}=await g(l,i);console.log(t,r),t.length===0?c():(h(t),i*15>=r&&(n.show({title:"ℹ️",message:"We're sorry, but you've reached the end of search results",color:"blue",position:"topRight"}),c()))}catch(t){console.error("Error during fetching data:",t.message),n.show({title:"⚠️",message:"An error occurred. Please try again later!",color:"red",position:"topRight"})}finally{A()}}
//# sourceMappingURL=index.js.map
