import{a as m,S as L,i as n}from"./assets/vendor-30VqbI-A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const v=m.defaults.API_KEY="49359087-343ead2b9467da8fb57304bcb",P=m.defaults.baseURL="https://pixabay.com/api/";async function g(s,t){const r={params:{key:v,q:s.trim(),image_type:"photo",orientation:"horizontal",page:t,per_page:15,safesearch:"true"}},o=await m.get(P,r),{hits:e,totalHits:a}=o.data;return{hits:e,totalHits:a}}let u=null;function S(){y.innerHTML=""}function h(s){R(s)}function q(){f.classList.remove("hidden")}function c(){f.classList.add("hidden")}const y=document.querySelector(".gallery"),f=document.querySelector(".btn-more");function R(s=[]){const t=s.map(r=>`<li class="gallery-item">
        <a href="${r.largeImageURL}" class="gallery-item-link">
        <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="text-info">
        <p><b>Likes:</b>${r.likes}</p>
        <p><b>Views:</b>${r.views}</p>
        <p><b>Comments:</b>${r.comments}</p>
        <p><b>Downloads:</b>${r.downloads}</p>
        </div>
        </li>`).join("");y.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new L(".gallery a",{caption:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}const E=document.querySelector(".form"),b=document.querySelector(".loader"),w=document.querySelector(".loader-bottom");function T(){b.classList.remove("hidden")}function p(){b.classList.add("hidden")}function x(){w.classList.remove("hidden")}function A(){w.classList.add("hidden")}f.addEventListener("click",$);E.addEventListener("submit",B);let l=null,i=1;async function B(s){s.preventDefault(),i=1,S();const t=s.currentTarget,{searchText:r}=t.elements;if(l=r.value.trim(),!l){n.show({title:"⛔",message:"Please write a search query!",color:"yellow",position:"topRight"});return}T(),c();try{const{hits:o,totalHits:e}=await g(l,i);if(!Array.isArray(o)){console.error("Invalid response structure. Hits is not an array."),n.show({title:"⚠️",message:"Unexpected response format. Please try again later!",color:"yellow",position:"topRight"}),p();return}if(o.length===0){n.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),p();return}h(o),o.length<e?q():c(),t.reset()}catch(o){let e="An unexpected error occurred. Please try again later!";o.response?e=`Server Error: ${o.response.data.message||o.message}`:o.request&&(e="Network Error: Failed to reach the server. Please check your internet connection."),n.show({title:"⚠️",message:e,color:"red",position:"topRight"}),console.error("Error:",o.message)}p()}async function $(s){i+=1,x();try{const{hits:t,totalHits:r}=await g(l,i);t.length===0?c():(h(t),i*15>=r&&(n.show({title:"ℹ️",message:"We're sorry, but you've reached the end of search results",color:"blue",position:"topRight"}),c())),H()}catch(t){console.error("Error during fetching data:",t.message),n.show({title:"⚠️",message:"An error occurred. Please try again later!",color:"red",position:"topRight"})}finally{A()}}function H(){const s=document.querySelector(".gallery-img");if(s){const t=s.getBoundingClientRect().height;window.scrollBy({top:t*2.5,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
