import{a as u,S as f,i as n}from"./assets/vendor-30VqbI-A.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const m=u.defaults.API_KEY="49359087-343ead2b9467da8fb57304bcb",g=u.defaults.baseURL="https://pixabay.com/api/";async function y(o){const a={params:{key:m,q:o.trim(),image_type:"photo",orientation:"horizontal",page:1,per_page:15,safesearch:"true"}},e=await u.get(g,a),{hits:r}=e.data;return r}let l=null;function h(){p.innerHTML=""}function b(o){h(),w(o)}function L(){d.classList.remove("hidden")}function c(){d.classList.add("hidden")}const d=document.querySelector(".loader"),p=document.querySelector(".gallery");function w(o=[]){p.innerHTML="";const s=o.map(t=>`<li class="gallery-item">
        <a href="${t.largeImageURL}" class="gallery-item-link">
        <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="text-info">
        <p><b>Likes:</b>${t.likes}</p>
        <p><b>Views:</b>${t.views}</p>
        <p><b>Comments:</b>${t.comments}</p>
        <p><b>Downloads:</b>${t.downloads}</p>
        </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",s),l?l.refresh():l=new f(".gallery a",{caption:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}const P=document.querySelector(".form");P.addEventListener("submit",v);async function v(o){o.preventDefault();const s=o.currentTarget,{searchText:t}=s.elements,a=t.value.trim();if(!a){n.show({title:"⛔",message:"Please write a search query!",color:"yellow",position:"topRight"});return}L();try{const e=await y(a);if(!Array.isArray(e)){console.error("Invalid response structure. Hits is not an array."),n.show({title:"⚠️",message:"Unexpected response format. Please try again later!",color:"red",position:"topRight"}),c();return}if(e.length===0){n.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),c();return}b(e),s.reset()}catch(e){let r="An unexpected error occurred. Please try again later!";e.response?r=`Server Error: ${e.response.data.message||e.message}`:e.request&&(r="Network Error: Failed to reach the server. Please check your internet connection."),n.show({title:"⚠️",message:r,color:"red",position:"topRight"}),console.error("Error:",e.message)}c()}
//# sourceMappingURL=index.js.map
